### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by shanchu815** [DukeNgn/Dog-facts-API-DEPRECATED-#9]
https://dog-facts-api.herokuapp.com/api/ & all its derivatives

keeps returning

[Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail]

**Comment by DucNgn** [comment]
Hi, sorry for the issue.

I've finished migrating the project to a new repo: [Dog-Facts-API-v2](https://github.com/DukeNgn/Dog-Facts-API-v2). the new API endpoint is at: https://www.dogfactsapi.ducnguyen.dev which is hosted on my own VM.

The CORS issue should be fixed now and the API should be more stable (no sleeping dynos which caused your issue)

**Comment by shanchu815** [comment]
Thanks! Does this mean that the old api has been taken down or is it still
up?

**Comment by DucNgn** [comment]
Hi @shanchu815 
I'll keep the old API up for a while, but it might be completely taken down in the future.
Keep in mind that it's running on the free tier on Heroku, so API might go down at the end of every month if the traffic is higher than the tier allows.

**Comment by shanchu815** [comment]
Thanks for letting me know!
